version: "3.9"

services:
  chembot:
    build: .
    container_name: chembot_app
    volumes:
      - ./models:/app/models
      - ./faiss_index:/app/faiss_index
      - ./hf_cache:/root/.cache/huggingface
    environment:
      - HF_MODEL_ID=${HF_MODEL_ID}
      - LOCAL_MODEL_ID=${LOCAL_MODEL_ID}
      - TRANSFORMERS_CACHE=/root/.cache/huggingface  # Save transformers locally
      - HUGGINGFACEHUB_API_TOKEN=${HUGGINGFACEHUB_API_TOKEN}
      - HF_REPO_ID=${HF_REPO_ID}
      - PATH_INDEX=${PATH_INDEX}
      - PATH_PDF=${PATH_PDF}
      - PROVIDER=${PROVIDER}
    ports:
      - "8000:8000"
    restart: unless-stopped
  # db:
  #   image: pgvector/pgvector:pg16
  #   environment:
  #     POSTGRES_DB: mydb
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"