"""
Author: Md Ismail Quraishi
Date: 14/03/2026
Purpose:
    To implement the core AI logic for ChemBot, a chemistry-focused chatbot.
    This module handles chemistry question answering, quiz generation, and
    answer grading using a local LLM via LangChain and Ollama.
"""

import os
import random
from dotenv import load_dotenv
from src.db.chembot_ai import ChemDB
from src.llm.factory import LLMFactory
from langchain_core.messages import HumanMessage, AIMessage
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder


chem_db = ChemDB()
load_dotenv()

prompt_base = ChatPromptTemplate.from_messages([
            ("system",
            """
        You are ChemBot, an AI chemistry teacher.

        Rules:
        - Only answer chemistry-related questions.
        - Use the provided context to answer.
        - If context is not relevant, answer from your knowledge.
        - If not chemistry-related, respond:
        "I can only answer chemistry-related questions."
        """),

            MessagesPlaceholder(variable_name="chat_history"),

            ("human",
            """
        Context:
        {context}

        Question:
        {question}
        """)
        ])
    

class ChatBotAI:


    """
    ChatBotAI handles the core conversational functionality of ChemBot.

    This class uses a local language model through LangChain and Ollama
    to answer user questions related to chemistry. It maintains a short
    conversation history to provide contextual responses while enforcing
    rules that restrict the chatbot to chemistry-related topics only.

    Responsibilities:
        - Process user chemistry questions
        - Maintain limited chat history for context
        - Generate responses using the LLM
        - Restrict responses to chemistry-related topics
    """


    def __init__(self, provider:str):

        """
        Initialize the ChatBotAI instance.

        This constructor sets up the core components required for the
        ChemBot conversational system, including:

        - Initializing chat history storage to maintain recent conversation context.
        - Loading the local language model via Ollama.
        - Creating the prompt template that defines the chatbot's role,
        rules, and response behavior.

        The prompt enforces that the chatbot only answers chemistry-related
        questions and rejects non-chemistry queries.
        """

        self.chat_history = []
        self.n_chunks:int = 3
        self.path_pdf:str = os.getenv("PATH_PDF")
        self.path_index:str = os.getenv("PATH_INDEX")
        self.llm = LLMFactory.create(provider=provider)
        self.prompt = prompt_base
        self.chain = self.prompt | self.llm


    def get_context(self, question:str):

        db = chem_db.get_faiss(path_pdf= self.path_pdf, index_path= self.path_index)
        context = "\n\n".join([content.page_content for content in db.similarity_search(question.strip(), k=self.n_chunks)])
        print(f"context fetched successfully!")
        return context


    async def ask_local(self, question:str, local_provider:bool=True):

        """
        Process a user question and generate a chemistry-focused response.

        This method sends the user's question along with recent conversation
        history to the language model. The model generates a response based
        on the defined prompt rules, ensuring answers remain related to
        chemistry topics.

        The conversation history is updated after each interaction so that
        future responses can use recent context.

        Args:
            question (str): The user's input question.

        Returns:
            str: The response generated by ChemBot.
        """

        context = self.get_context(question=question)
        print(f"CONTEXT: {context}")
        response = await self.chain.invoke({
            "chat_history": self.chat_history,
            "question": question,
            "context": context
        })

        answer = response.content
        self.chat_history.append(HumanMessage(content=question))
        self.chat_history.append(AIMessage(content=answer))
        return answer
    

    def ask(self, question:str):

        """
        Process a user question and generate a chemistry-focused response.

        This method sends the user's question along with recent conversation
        history to the language model. The model generates a response based
        on the defined prompt rules, ensuring answers remain related to
        chemistry topics.

        The conversation history is updated after each interaction so that
        future responses can use recent context.

        Args:
            question (str): The user's input question.

        Returns:
            str: The response generated by ChemBot.
        """

        context = self.get_context(question=question)
        print(f"CONTEXT: {context}")
        response = self.chain.invoke({
            "chat_history": self.chat_history,
            "question": question,
            "context": context
        })

        answer = response.content
        self.chat_history.append(HumanMessage(content=question))
        self.chat_history.append(AIMessage(content=answer))
        return answer

